version: '3'
services:
  
  #LOAD BALANCER FOR API
  loadbalancer-api:
    build: ./LoadBalancer-api/
    networks:
      - quiznet
    ports:
      - "9000:80"
    depends_on:
      - api

  #LOAD BALANCER FOR REACT CLIENT
  loadbalancer-app:
    build: ./LoadBalancer-app/
    networks:
      - quiznet
    ports:
      - "3000:80"
    depends_on:
      - client

  api: 
    build: ./todo-api/
    networks:
      - quiznet
    ports:
      - "9001:9000"
    environment:
      SERVER_TAG: "api-service-1"
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "root123#"
      DATABASE_OPTION_DATABASE: "todosDB"

  api-2: 
    build: ./todo-api/
    networks:
      - quiznet
    ports:
      - "9002:9000"
    environment:
      SERVER_TAG: "api-service-2"
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "root123#"
      DATABASE_OPTION_DATABASE: "todosDB"
 
      # SERVER_TAG: "api-service-1"
      # DATABASE_SERVER: "sqlserver"
      # DATABASE_AUTHENTICATION_TYPE: "default"
      # DATABASE_AUTHENTICATION_USERNAME: "fonse"
      # DATABASE_AUTHENTICATION_PASSWORD: "quiz02112021"
      # DATABASE_OPTION_DATABASE: "todosDB"

    depends_on:
      - database
    # links:
    #   - "database"

  client:
    build: 
      context: ./todo-app/
      args:
        - API_HOST="http://localhost:9000/api/todos"
    networks:
      - quiznet
    ports:
      - "3001:80"
    depends_on:
      - database

  client-2:
    build: 
      context: ./todo-app/
      args:
        - API_HOST="http://localhost:9000/api/todos"
    networks:
      - quiznet
    ports:
      - "3002:80"
    depends_on:
      - database

  database:
    image: "mcr.microsoft.com/mssql/server"
    hostname: "sqlserver"
    networks:
      - quiznet
    volumes:
      - quizdata:/var/opt/mssql/
    environment:
      SA_PASSWORD: "root123#"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

#TODO Networking and loadbalance for all containers
networks:
  quiznet:
    driver: bridge

volumes:
  quizdata:
