version: '3'
services:
  
  #LOAD BALANCER FOR API
  loadbalancer-api:
    build: ./LoadBalancer-api/
    networks:
      - quiznet
    ports:
      - "9000:80"
    depends_on:
      - api-1
      - api-2
      - api-3
      - api-4
      - api-5
      - api-6
      - api-7
      - api-8
      - api-9
      - api-10

  #LOAD BALANCER FOR REACT CLIENT
  loadbalancer-app:
    build: ./LoadBalancer-app/
    networks:
      - quiznet
    ports:
      - "3000:80"
    depends_on:
      - client-1
      - client-2
      - client-3
      - client-4
      - client-5
      - client-6

  api-1: 
    build: ./todo-api/
    networks:
      - quiznet
    ports:
      - "9001:9000"
    environment:
      SERVER_TAG: "api-service-1"
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "root123#"
      DATABASE_OPTION_DATABASE: "todosDB"

  api-2: 
    build: ./todo-api/
    networks:
      - quiznet
    ports:
      - "9002:9000"
    environment:
      SERVER_TAG: "api-service-2"
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "root123#"
      DATABASE_OPTION_DATABASE: "todosDB"

  api-3: 
    build: ./todo-api/
    networks:
      - quiznet
    ports:
      - "9003:9000"
    environment:
      SERVER_TAG: "api-service-3"
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "root123#"
      DATABASE_OPTION_DATABASE: "todosDB"
  api-4: 
    build: ./todo-api/
    networks:
      - quiznet
    ports:
      - "9004:9000"
    environment:
      SERVER_TAG: "api-service-4"
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "root123#"
      DATABASE_OPTION_DATABASE: "todosDB"
  api-5: 
    build: ./todo-api/
    networks:
      - quiznet
    ports:
      - "9005:9000"
    environment:
      SERVER_TAG: "api-service-5"
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "root123#"
      DATABASE_OPTION_DATABASE: "todosDB"
  api-6: 
    build: ./todo-api/
    networks:
      - quiznet
    ports:
      - "9006:9000"
    environment:
      SERVER_TAG: "api-service-6"
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "root123#"
      DATABASE_OPTION_DATABASE: "todosDB"
  api-7: 
    build: ./todo-api/
    networks:
      - quiznet
    ports:
      - "9007:9000"
    environment:
      SERVER_TAG: "api-service-7"
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "root123#"
      DATABASE_OPTION_DATABASE: "todosDB"
  api-8: 
    build: ./todo-api/
    networks:
      - quiznet
    ports:
      - "9008:9000"
    environment:
      SERVER_TAG: "api-service-8"
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "root123#"
      DATABASE_OPTION_DATABASE: "todosDB"
  api-9: 
    build: ./todo-api/
    networks:
      - quiznet
    ports:
      - "9009:9000"
    environment:
      SERVER_TAG: "api-service-9"
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "root123#"
      DATABASE_OPTION_DATABASE: "todosDB"
  api-10: 
    build: ./todo-api/
    networks:
      - quiznet
    ports:
      - "9010:9000"
    environment:
      SERVER_TAG: "api-service-10"
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "root123#"
      DATABASE_OPTION_DATABASE: "todosDB"
   
  client-1:
    build: 
      context: ./todo-app/
      args:
        - API_HOST="http://localhost:9000/api/todos"
    networks:
      - quiznet
    ports:
      - "3001:80"

  client-2:
    build: 
      context: ./todo-app/
      args:
        - API_HOST="http://localhost:9000/api/todos"
    networks:
      - quiznet
    ports:
      - "3002:80"
  client-3:
    build: 
      context: ./todo-app/
      args:
        - API_HOST="http://localhost:9000/api/todos"
    networks:
      - quiznet
    ports:
      - "3003:80"
  client-4:
    build: 
      context: ./todo-app/
      args:
        - API_HOST="http://localhost:9000/api/todos"
    networks:
      - quiznet
    ports:
      - "3004:80"
  client-5:
    build: 
      context: ./todo-app/
      args:
        - API_HOST="http://localhost:9000/api/todos"
    networks:
      - quiznet
    ports:
      - "3005:80"
  client-6:
    build: 
      context: ./todo-app/
      args:
        - API_HOST="http://localhost:9000/api/todos"
    networks:
      - quiznet
    ports:
      - "3006:80"

  database:
    image: "mcr.microsoft.com/mssql/server"
    hostname: "sqlserver"
    networks:
      - quiznet
    volumes:
      - quizdata:/var/opt/mssql/
    environment:
      SA_PASSWORD: "root123#"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

#TODO Networking and loadbalance for all containers
networks:
  quiznet:
    driver: bridge

volumes:
  quizdata:
